- name: setup DB mysql
  hosts: db
  become: yes
  tasks:
     - name: copy sql repo
       copy:
         src: /root/expense-latest/mysql.repo
         dest: /etc/yum.repos.d/mysql.repo
     - name: shell command to disable
       shell: dnf module disable mysql -y
     - name: install mysql software
       dnf:
         name: mysql-community-server
         state: present
     - name: start mysqld
       systemd:
          name: mysqld
          state: restarted
          enabled: yes
     - name: "set mysqlpasswd"
       shell: mysql_secure_installation --set-root-pass {{sql_passwd}}
